server:
  http:
    addr:             :8000
    shutdown_timeout: 0s

logger:
  level: debug

crypt:
  pgp:
    pgp_key: "PGP password"

storage:
  postgres:
    host:     localhost
    port:     5432
    user:     user
    password: pass
    database: mydb
    ssl_mode: disable
