CREATE TABLE credits
(
    id            int4 GENERATED BY DEFAULT AS IDENTITY,
    account_id    int4                                  NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    principal     numeric(12, 2)                        NOT NULL,
    interest_rate numeric(5, 4)                         NOT NULL,
    term_months   int4                                  NOT NULL,
    start_date    date                                  NOT NULL,
    status        varchar(20) DEFAULT 'active'          NOT NULL,
    created_at    timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT credits_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_credits_account_id ON credits (account_id);
