CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE clients
(
    id         int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name"     varchar                               NOT NULL,
    username   varchar                               NOT NULL,
    "password" varchar                               NOT NULL,
    email      varchar                               NOT NULL,
    "admin"    bool DEFAULT false                    NOT NULL,
    CONSTRAINT clients_email UNIQUE (email),
    CONSTRAINT clients_pk PRIMARY KEY (id),
    CONSTRAINT clients_username UNIQUE (username)
);


CREATE TABLE accounts
(
    id        int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id int4                                  NOT NULL, -- Владелец счёта
    balance   float8 DEFAULT 0                      NOT NULL, -- Баланс счёта
    "number"  varchar                               NOT NULL, -- Номер счёта
    CONSTRAINT accounts_pk PRIMARY KEY (id),
    CONSTRAINT accounts_unique UNIQUE (number)
);

CREATE INDEX idx_accounts_client_id ON accounts (client_id);