CREATE TABLE cards
(
    id         int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id  int4                                  NOT NULL REFERENCES clients (id) ON DELETE CASCADE, -- Владелец карты
    account_id int4                                  NOT NULL,                                           -- Счёт привязки
    cardnum    bytea                                 NOT NULL,                                           -- Номер карты в зашифрованном виде
    expire     timestamp                             NOT NULL,                                           -- Дата окончания карты
    cvv        varchar                               NOT NULL,                                           -- CVV в шифрованном виде
    CONSTRAINT cards_number UNIQUE (cardnum),
    CONSTRAINT cards_pk PRIMARY KEY (id)
);

CREATE INDEX idx_cards_user_id ON cards (client_id);
